{{- $rootContext := . }}
{{- $values := .Values }}
{{- $release := .Release }}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spark-on-k8s.serviceAccountName" . }}
  labels:
    {{- include "spark-on-k8s.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- if eq .Values.namespaces "*" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  {{- if .Values.readOnly }}
  name: {{ include "spark-on-k8s.fullname" . }}-view
  {{- else }}
  name: {{ include "spark-on-k8s.fullname" . }}-edit
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "spark-on-k8s.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  {{- if .Values.readOnly }}
  name: view
  {{- else }}
  name: edit
  {{- end }}
  apiGroup: rbac.authorization.k8s.io
{{- else }}
{{- $namespaces := split "," .Values.namespaces}}
{{- range $namespace := $namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "spark-on-k8s.fullname" $rootContext }}
  namespace: {{ $namespace }}
  labels:
    {{- include "spark-on-k8s.labels" $rootContext | nindent 4 }}
{{- if $values.readOnly }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
{{- else }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "delete"]
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  {{- if $values.readOnly }}
  name: {{ include "spark-on-k8s.fullname" $rootContext }}-view
  {{- else }}
  name: {{ include "spark-on-k8s.fullname" $rootContext }}-edit
  {{- end }}
  namespace: {{ $namespace }}
  labels:
    {{- include "spark-on-k8s.labels" $rootContext | nindent 4 }}
subjects:
    - kind: ServiceAccount
      name: {{ include "spark-on-k8s.serviceAccountName" $rootContext }}
      namespace: {{ $release.Namespace }}
roleRef:
    kind: Role
    name: {{ include "spark-on-k8s.fullname" $rootContext }}
    apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
{{- end }}