{{- $rootContext := . }}
{{- $values := .Values }}
{{- $release := .Release }}
{{- if and .Values.sparkHistory.enabled .Values.sparkHistory.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spark-on-k8s.sparkHistory.serviceAccountName" . }}
  labels:
    {{- include "spark-on-k8s.labels" . | nindent 4 }}
  {{- with .Values.sparkHistory.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.sparkHistory.serviceAccount.automount }}
{{- end }}
